### ISSUE TITLE
how to fix bug tensorflow 

### ISSUE THREAD

**Issue by chien334** [cipherdev/src#11]
WARNING:tensorflow:From /home/dev/catkin_ws/src/lane_detect/src/traffic_signs/Traffic_Signs_Recognition.py:119: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From /home/dev/catkin_ws/src/lane_detect/src/traffic_signs/Traffic_Signs_Recognition.py:151: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/dev/catkin_ws/src/lane_detect/src/traffic_signs/Traffic_Signs_Recognition.py:173: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/dev/catkin_ws/src/lane_detect/src/traffic_signs/Traffic_Signs_Recognition.py:190: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Traceback (most recent call last):
  File "/home/dev/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/dev/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/dev/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dev/catkin_ws/src/lane_detect/src/traffic_signs/Traffic_Signs_Recognition.py", line 190, in <module>
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits, y))
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 3238, in softmax_cross_entropy_with_logits
    logits)
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2994, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by huyle-anh** [comment]
I don't see the error on your messg. Add more the logs would be helpful for me. 
--HuyLe
